### ISSUE TITLE
fiche organisation en double

### ISSUE THREAD

**Issue by martyKN** [ecolabdata/ckanext-dsfr#16]
la fiche de la ddtm 30 est la seule a être la, mais elle est en double.
https://data.developpement-durable.gouv.fr/organization/

**Comment by bchossat** [comment]
Il ne s'agit pas d'un bug graphique, deux organisations avec le même nom sont bien inscrites en base de données. Probablement que l'organisation a été créée deux fois.

Via l'API CKAN : GET https://data.developpement-durable.gouv.fr/api/3/action/organization_list
Renvoie : {"help": "https://data.developpement-durable.gouv.fr/api/3/action/help_show?name=organization_list", "success": true, "result": ["ddt-30189-01", "ddt-30189-02"]}

Via l'IHM,
https://data.developpement-durable.gouv.fr/organization/about/ddt-30189-01 ==> 123 jeux de données associés
https://data.developpement-durable.gouv.fr/organization/about/ddt-30189-02 ==> 0 jeux de données associés

L'organisation d'ID "ddt-30189-02" peut être supprimée simplement sans nécessiter de purge de données préalable.

Via les API de CKAN

POST https://data.developpement-durable.gouv.fr/api/3/action/organization_delete avec le header Authorization=TOKEN_CKAN et le body JSON suivant:
{
    "id":"ddt-30189-02"
}

L'exécution de cet appel renvoie : 
{
    "help": "https://data.developpement-durable.gouv.fr/api/3/action/help_show?name=organization_delete",
    "success": true,
    "result": null
}

L'organisation est bien supprimée, confirmé via l'IHM.
![image](https://user-images.githubusercontent.com/91319383/206727269-14bba0c0-6a44-42ff-8438-aa6d6d7f0654.png)


Je vous laisse clôturer le ticket.
